const {
  VITE_DISABLE_DOCKER,
  VITE_NO_DOCKER_API_PORT,
  VITE_APP_ANALYSE_BUNDLE,
  VITE_NO_DOCKER_APP_PORT
} = import.meta.env;

export const DISABLE_DOCKER = VITE_DISABLE_DOCKER;
export const NO_DOCKER_API_PORT = VITE_NO_DOCKER_API_PORT;
export const APP_ANALYSE_BUNDLE = VITE_APP_ANALYSE_BUNDLE;
export const NO_DOCKER_APP_PORT = VITE_NO_DOCKER_APP_PORT;
